baseurl = "http://acm.socialworkstats.org/"
title = "Analytical Case Management"
theme = "hugo-nederburg-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination

[params]
  slogan = "Social service case management based on measurement and analysis"
  description = "A Hugo page designed to communicate to the public about the analytical case management pilot courses being offered at the University of Washington School of Social Work." # meta description
  author = "Joe Mienko"
  authorLink = "https://github.com/mienkoja"
  bio = [
    "Joe Mienko is the creator of analytical case management. He is a senior research scientist and lecturer at the <a href='http://socialwork.uw.edu'>University of Washington School of Social Work</a>"]
  copyright = [
    "&copy; 2018 Joe Mienko",
    "Nederburg-hack Hugo Theme by [Joe Mienko](https://github.com/mienkoja).",
    "A port of Nederburg by Göran Svensson, with some superficial hacks by the author."
  ]


  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below (it is also used in Gravatar for the bio).
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "mienko@uw.edu"

  # Nav links in the side bar
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "About"
  url = "about/"
  weight = 2

  [[menu.main]]
  name = "Get in touch"
  url = "contact/"
  weight = 3
  
  [[menu.main]]
  name = "Register"
  url = "registration/"
  weight = 4

  [params.social]
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  email         = "mienko@uw.edu"
  twitter       = "full profile url in twitter"
  linkedin      = "full profile url in linkedin"
  stackoverflow = "full profile url in stackoverflow"
  #instagram     = "full profile url in instagram"
  github        = "full profile url in github"
  #pinterest     = "full profile url in pinterest"
